// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWULzHfzuZdZn6_fV7DNj9REFMtkw5hzs',
    appId: '1:1074315063110:web:13db24d57d09309c693f47',
    messagingSenderId: '1074315063110',
    projectId: 'syriagoal-17e93',
    authDomain: 'syriagoal-17e93.firebaseapp.com',
    storageBucket: 'syriagoal-17e93.firebasestorage.app',
    measurementId: 'G-RBDJG0RJX8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvO7kusr_QIu9RiFhdGjpBeyNJ58hr2Gw',
    appId: '1:1074315063110:android:cd71e58fc156fb18693f47',
    messagingSenderId: '1074315063110',
    projectId: 'syriagoal-17e93',
    storageBucket: 'syriagoal-17e93.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHoGe9saZVxh3CpvO9Xo0UEnhgt4LCadE',
    appId: '1:1074315063110:ios:8f4fe0630088d48c693f47',
    messagingSenderId: '1074315063110',
    projectId: 'syriagoal-17e93',
    storageBucket: 'syriagoal-17e93.firebasestorage.app',
    iosBundleId: 'com.example.syriagoal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHoGe9saZVxh3CpvO9Xo0UEnhgt4LCadE',
    appId: '1:1074315063110:ios:8f4fe0630088d48c693f47',
    messagingSenderId: '1074315063110',
    projectId: 'syriagoal-17e93',
    storageBucket: 'syriagoal-17e93.firebasestorage.app',
    iosBundleId: 'com.example.syriagoal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWULzHfzuZdZn6_fV7DNj9REFMtkw5hzs',
    appId: '1:1074315063110:web:7c9a187bd62cb695693f47',
    messagingSenderId: '1074315063110',
    projectId: 'syriagoal-17e93',
    authDomain: 'syriagoal-17e93.firebaseapp.com',
    storageBucket: 'syriagoal-17e93.firebasestorage.app',
    measurementId: 'G-EV6PX4HPLV',
  );
}
